package org.example.ExerciciosClasses

fun main(){
    val bola = ExercicioClasse1("Amarelo",5.0,"Metal")
    bola.exercicio1Mensagem()
    println()
    val quadrado = ExercicioClasse2(4.0)
    quadrado.exercicio2AlterarLado()
    quadrado.exercicio2Imprimir()
    println()
    val retangulo = ExercicioClasse3(120,50)
    retangulo.imprimir()
    println()
    val pessoa = ExercicioClasse4("Jotaro Joestar",17, 95.5, 1.95)
    pessoa.imprimirPessoa()
    println()
    pessoa.envelhecer()
    println()
    pessoa.imprimirPessoa()
    println()
    pessoa.engordar()
    println()
    pessoa.imprimirPessoa()
    println()
}